version: '3.8'
services:
  movies:
    image: gopinadh/paytmmoviesss:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: gopinadh/paytmtrainnn:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: gopinadh/paytmdthhh
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: gopinadh/paytmrechargeee:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
